// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjA_ylqXj-24Xu6W50wcLTN-CzYSfzoZw',
    appId: '1:415313803169:web:e03eaa28fd46b880d7bde0',
    messagingSenderId: '415313803169',
    projectId: 'lab-assignment-dd29d',
    authDomain: 'lab-assignment-dd29d.firebaseapp.com',
    storageBucket: 'lab-assignment-dd29d.firebasestorage.app',
    measurementId: 'G-7KXFRJBTRN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxvZlgPjAMJtpMKpWxabM6WfoQqCbcVKI',
    appId: '1:415313803169:android:0da6e7ebefe42a8fd7bde0',
    messagingSenderId: '415313803169',
    projectId: 'lab-assignment-dd29d',
    storageBucket: 'lab-assignment-dd29d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBm1ZtBctofzv_U_WcA43MiIdqrWSB-Wbo',
    appId: '1:415313803169:ios:c05a3f6dd16c7f55d7bde0',
    messagingSenderId: '415313803169',
    projectId: 'lab-assignment-dd29d',
    storageBucket: 'lab-assignment-dd29d.firebasestorage.app',
    iosBundleId: 'com.example.labAssignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBm1ZtBctofzv_U_WcA43MiIdqrWSB-Wbo',
    appId: '1:415313803169:ios:c05a3f6dd16c7f55d7bde0',
    messagingSenderId: '415313803169',
    projectId: 'lab-assignment-dd29d',
    storageBucket: 'lab-assignment-dd29d.firebasestorage.app',
    iosBundleId: 'com.example.labAssignment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjA_ylqXj-24Xu6W50wcLTN-CzYSfzoZw',
    appId: '1:415313803169:web:37a9afd330baa2dfd7bde0',
    messagingSenderId: '415313803169',
    projectId: 'lab-assignment-dd29d',
    authDomain: 'lab-assignment-dd29d.firebaseapp.com',
    storageBucket: 'lab-assignment-dd29d.firebasestorage.app',
    measurementId: 'G-BZ7PKBG57K',
  );
}
